/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ikki_3d (https://sketchfab.com/ikki_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubber-duck-f1de4fc390db4266a509b9739350512a
Title: Rubber duck
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Float, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		defaultMaterial: THREE.Mesh;
	};
	materials: {
		material: THREE.MeshStandardMaterial;
	};
};

export function Model(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("/models/rubber_duck.glb") as GLTFResult;
	return (
		<Float rotationIntensity={2}>
			<group {...props} dispose={null}>
				<group rotation={[-Math.PI / 2, 0, 0]}>
					<group rotation={[Math.PI / 2, 0, 0]}>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.defaultMaterial.geometry}
							material={materials.material}
							position={[0, 173.286, -2.915]}
							rotation={[-Math.PI / 2, 0, 0]}
							scale={[0.901, 1.086, 1.022]}
						/>
					</group>
				</group>
			</group>
		</Float>
	);
}

useGLTF.preload("/models/rubber_duck.glb");
